# Description: Configuration file for the MosaiCatcher pipeline
# This file is used to define the configuration of the MosaiCatcher pipeline
# It is used to define the data collections and workflows that are available
# in the system.

# Version of the configuration file
name: "Strand-Seq data analysis"

data_management_platform_project_url: "https://labid.embl.org/core/projects/default/5baa8f07-bd00-46e7-b3cb-ec79d01f6f3c"
# Workflows that are available in the system
workflows:
  ## Workflow for the MosaiCatcher pipeline

    # The name of the workflow
  - name: "mosaicatcher-pipeline2"
    # Engine that is used to run the workflow
    engine: 
      name: "snakemake"
    
    description: "Strand-Seq SV calling framework"

    # The URL of the repository that contains the workflow
    repository_url: "https://github.com/friendsofstrandseq/mosaicatcher-pipeline"

    # The configuration to retrieve workflow data
    config:

      # TODO: to turn into a dict (location - regex)
      # The location of the runs - multiple locations can be specified
      parent_runs_location:
        # - "${DEPICTIO_BACKEND_EXAMPLE_DATA_VOLUME_HOST}/StrandSeq/HGSVC"
        # - "{DATA_LOCATION}/mosaicatcher-pipeline-2024"
        - "/Users/tweber/Data/mosaicatcher-pipeline-2024"
        # - "${DEPICTIO_BACKEND_DATA_VOLUME_HOST}/mosaicatcher-pipeline-2024"
        # - "/app/depictio-example-data/mosaicatcher-pipeline-2024"

      # Regular expression to match the runs
      runs_regex: ".*"

    # Data collections that are associated with the workflow
    data_collections:


      # The tag that is used to identify the data collection
      - data_collection_tag: "mosaicatcher_stats"

        # A description of the data collection
        description: "Statistics file generated by MosaiCatcher"

        # The configuration of the data collection
        config:
          # The type of the data collection (options: Table, JBrowse2)
          type: "Table"

          # The metatype of the data collection (options: Metadata, Aggregate ; Metadata corresponds to a single annotation file, Aggregate to the aggregation of multiple files into a single dataframe)
          metatype: "Aggregate"

          # A regular expression that is used to match the files specific of the data collection
          # files_regex: ".*.info_raw"
          scan:
            mode: recursive
            scan_parameters:
                regex_config: 
                    pattern: ".*.info_raw"

          # The specific properties of the data collection - is related to the type of the data collection (Table here)
          dc_specific_properties:

            # The format of the data collection
            format: "TSV"

            # The configuration of the Polars DataFrame for the data collection
            polars_kwargs:

              skip_rows: 13
              separator: "\t"
              # Other options for polars_kwargs:
              # - column_types
              # - column_names
              # ...

            # The columns that are kept in the table - all other columns are dropped
            keep_columns:
              - "sample"
              - "cell"
              - "mapped"
              - "dupl"
              - "pass1"
              - "good"
            columns_description:
              sample: "Sample ID"
              cell: "Cell ID"
              mapped: "Total number of reads seen"
              dupl: "Reads filtered out as PCR duplicates"
              pass1: "Coverage compliant cells (binary)"
              good: "Reads used for counting"

          # Allow to join the data collections - used for table join
          join:
            # The columns that are used to join the data collections
            on_columns:
              - "sample"
              - "cell"
            # The type of join that is used to join the data collections
            how: "inner"
            # The list of data collections that are used to join the data collection
            with_dc:
              - "ashleys_labels"

      - data_collection_tag: "mosaicatcher_samples_metadata"
        description: "Metadata file for MosaiCatcher samples"
        config:
          type: "Table"
          metatype: "Metadata"
          scan: 
            mode: single
            scan_parameters: 
                filename: "/Users/tweber/Data/mosaicatcher-pipeline-2024/mosaicatcher_samples_metadata_2024.xlsx"
          dc_specific_properties:
            format: "XLSX"
          join:
            on_columns:
              - "sample"
            how: "inner"
            with_dc:
              - "mosaicatcher_stats"


